import { RefList } from '../models/ref-list';

export enum FeatureCodes {
  setting = 'setting',
  countries = 'countries',
  stage = 'stage',
  typePrice = 'type-price',
  destination = 'destination',
  contracts = 'contracts',
  administration = 'administration',
  company = 'company',
  features = 'features',
  groups = 'groups',
  users = 'users',
  paramProject = 'param-project',
  account = 'account',
  profile = 'profile',
  thirdPartyType = 'third-party-type',
  tms = 'tms',
  thirdParty = 'third-party',
  customer = 'customer',
  supplier = 'supplier',
  inventory = 'inventory',
  userFeatures = 'user-features',
  companyProduct = 'company-product',

  typeProduct = 'type-product',
  category = 'category',
  subcategory = 'subcategory',
  product = 'product',
  products = 'products',
  store = 'store',
}

export const listFeatureActions: RefList<FeatureCodes>[] = [
  { key: FeatureCodes.setting, value: 'Setting' },
  { key: FeatureCodes.countries, value: 'Countries' },
  { key: FeatureCodes.stage, value: 'Stage' },
  { key: FeatureCodes.typePrice, value: 'Type Price' },
  { key: FeatureCodes.destination, value: 'Destination' },
  { key: FeatureCodes.contracts, value: 'Contracts' },
  { key: FeatureCodes.administration, value: 'Administration' },
  { key: FeatureCodes.company, value: 'Company' },
  { key: FeatureCodes.features, value: 'Features' },
  { key: FeatureCodes.groups, value: 'Groups' },
  { key: FeatureCodes.users, value: 'Users' },
  { key: FeatureCodes.paramProject, value: 'Params Project' },
  { key: FeatureCodes.account, value: 'Account' },
  { key: FeatureCodes.profile, value: 'Profile' },
  { key: FeatureCodes.thirdPartyType, value: 'Third party type' },
  { key: FeatureCodes.tms, value: 'TMS' },
  { key: FeatureCodes.thirdParty, value: 'Third party' },
  { key: FeatureCodes.customer, value: 'Customer' },
  { key: FeatureCodes.supplier, value: 'Supplier' },
  { key: FeatureCodes.inventory, value: 'Inventory' },
  { key: FeatureCodes.userFeatures, value: 'user-features' },
  { key: FeatureCodes.companyProduct, value: 'company-product' },
  { key: FeatureCodes.typeProduct, value: 'type-product' },
  { key: FeatureCodes.category, value: 'category' },
  { key: FeatureCodes.subcategory, value: 'subcategory' },
  { key: FeatureCodes.product, value: 'product' },
  { key: FeatureCodes.products, value: 'products' },
  { key: FeatureCodes.store, value: 'store' },
];
